In [1]:
import numpy as np

Produto Escalar (Interno)

In [ ]:
A = np.array([[1, 2], [3, 4]])
A @ np.array([5, 6]) # Produto de matriz e vetor -- 1 * 5 + 2 * 6 = 17, 3 * 5 + 4 * 6 = 39

array([17, 39])

Cosseno

In [ ]:
cos = np.dot(A.flatten(), np.array([5, 6, 7, 8])) / (np.linalg.norm(A.flatten()) * np.linalg.norm(np.array([5, 6, 7, 8]))) # Cosseno do ângulo entre A e outro vetor
print("Cosseno do ângulo entre A e [5, 6, 7, 8]:", cos) 

a = np.array([1, 2])
b = np.array([2, -1])

cos_ab = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)) # Cosseno do ângulo entre a e b, linalg.norm calcula a norma (magnitude) do vetor
print("Cosseno do ângulo entre a e b:", cos_ab)

Cosseno do ângulo entre A e [5, 6, 7, 8]: 0.9688639316269662
Cosseno do ângulo entre a e b: 0.0


Slicing

In [12]:
print(A[0, 1]) # Acessando o elemento na primeira linha e segunda coluna (índice 0, 1)
print(A[:1]) # Acessando a primeira linha da matriz A 

2
[[1 2]]


Normas e Distância

In [7]:
normaL1 = np.linalg.norm(A, 1) # Norma L1 da matriz A
normaL2 = np.linalg.norm(A, 2) # Norma L2 da matriz A
normaLinf = np.linalg.norm(A, np.inf) # Norma L-infinito da matriz A
distanciaL1 = np.linalg.norm(A - np.array([[5, 6], [7, 8]]), 1) # Distância L1 entre A e outra matriz

print("Norma L1:", normaL1) # Somatório simples dos valores absolutos dos elementos da matriz
print("Norma L2:", normaL2) # Raiz quadrada da soma dos quadrados dos elementos da matriz
print("Norma L-infinito:", normaLinf) # Valor máximo absoluto entre os elementos da matriz
print("Distância L1 entre A e [[5, 6], [7, 8]]:", distanciaL1) # |A - B|_1

Norma L1: 6.0
Norma L2: 5.464985704219043
Norma L-infinito: 7.0
Distância L1 entre A e [[5, 6], [7, 8]]: 8.0


Matrizes especiais

In [16]:
print("Matriz A:\n", A)
print("Transposta de A:\n", A.T)
print("Inversa de A:\n", np.linalg.inv(A))
print("Matriz Identidade 2x2:\n", np.eye(2))

Matriz A:
 [[1 2]
 [3 4]]
Transposta de A:
 [[1 3]
 [2 4]]
Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Matriz Identidade 2x2:
 [[1. 0.]
 [0. 1.]]


Derivada (Inclinação de um ponto)

In [18]:
f = lambda x: x**2 + 2*x + 1 # Função
h = 1e-5 # Ordem de erro para a aproximação da derivada
print("Derivada numérica de f em x=1:", (f(1 + h) - f(1 - h)) / (2 * h)) # Derivada numérica usando a fórmula central

Derivada numérica de f em x=1: 4.000000000004


Gradiente

In [19]:
# O gradiente indica a direção de maior crescimento da função;
# Em IA, usando o gradiente descendente, podemos encontrar o mínimo de uma função, que é útil para otimização de modelos.

X = np.array([[1, 2], [3, 4], [5, 6]]) # Matriz de características (3 amostras, 2 características)
y = np.array([1, 2, 3]) # Vetor de rótulos (3 amostras)
w = np.array([0.5, 0.5]) # Vetor de pesos (2 características)
n = X.shape[0] # Número de amostras

grad = 2 / n * X.T @ (X @ w - y) # Cálculo do gradiente da função de custo para regressão linear
print("Gradiente da função de custo:", grad) # Mostra o gradiente, que indica a direção de maior crescimento da função de custo

Gradiente da função de custo: [11.66666667 14.66666667]


### Exercício Guiado

In [ ]:
rng = np.random.default_rng(42) # Gerador de números aleatórios
n, d = 10_000, 5
X = rng.normal(size=(n, d)) # Matriz de características com 10.000 amostras e 5 características
w = rng.normal(size=d) # Vetor de pesos com 5 elementos
y = X @ w + rng.normal(scale=0.1, size=n) # Adicionando ruído aos rótulos

# Cinco passos, sempre na mesma ordem:

# 1. Produto Interno;
# 2. Todas as previsões;
# 3. Distância entre pares de pontos;
# 4. MSE e Gradiente;
# 5. Conferir o Gradiente e Cronometrar.
# Em cada passo: laço, versão vetorizada, np.allclose entre as duas versões, %timeit nas duas.

#### 1. Produto Interno

In [ ]:
x = X[0] # (5,)

# Com laço
total = 0.0
for j in range(d):
    total += x[j] * w[j]

# Vetorizado
total_v = X[0] @ w # ()
print(np.isclose(total, total_v))

True


#### 2. Todas as Previsões

In [35]:
y_hat = np.zeros(n) # (10_000,)

# Com laço
for i in range(n):
    for j in range(d):
        y_hat[i] += X[i, j] * w[j]

# Vetorizado
y_hat_v = X @ w # (10_000,)
print(np.allclose(y_hat, y_hat_v)) # True
%timeit X @ w

True
19.2 μs ± 636 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### 3. Distância entre Pares de Pontos

In [40]:
# Com laço
A, B = X[:200], X[:50]
D = np.zeros((200, 50)) # (200, 50)
for i in range(200):
    for j in range(50):
        D[i, j] = np.linalg.norm(A[i] - B[j]) # Distância entre pares de pontos

# Vetorizado

diff = A[:, None, :] - B[None, :, :] # (200, 50, 5)
D_v = np.sqrt((diff ** 2).sum(axis=2)) # (200, 50)
print(np.allclose(D, D_v))

True


#### 4. MSE e Gradiente

In [41]:
# Com laço
w0 = np.zeros(d)
mse, grad = 0.0, np.zeros(d)
for i in range(n):
    erro = X[i] @ w0 - y[i]
    mse += erro ** 2 / n
    for j in range(d):
        grad[j] += 2 * erro * X[i, j] / n

# Vetorizado

erro = X @ w0 - y # (10_000,)
mse_v = (erro ** 2).mean() # ()
grad_v = 2 / n * X.T @ erro # (5,)
print(np.isclose(mse, mse_v)) # True
print(np.allclose(grad, grad_v)) # True

True
True


#### 5. Conferir o Gradiente e Cronometrar

In [42]:
def mse_de(w):
    return np.mean((X @ w - y) ** 2)

def grad_numerico(f, w, h=1e-6):
    g = np.zeros_like(w)
    for j in range(len(w)):
        e = np.zeros_like(w)
        e[j] = h
        g[j] = (f(w + e) - f(w - e)) / (2 * h)
    return g

print(np.allclose(grad_v, grad_numerico(mse_de, w0))) # True

True
